export const GAME_CONFIGURATIONS = {
  MAX_NUMBER_PLAYERS: 10,
  MAX_NUMBER_FRAMES_PER_PLAYER: 10,
  MAXIMUM_NUMBER_THROWS_PER_ROUND: 2,
  MAX_NUMBER_POINTS_PER_PLAYER: 300,
  MAX_NUMBER_PINS: 10
};

export enum TechnicalTerms {
  'STRIKE' = 'STRIKE',
  'TURKEY' = 'TURKEY',
  'SPARE' = 'SPARE',
  'MOTHER_LOVE' = 'MOTHER-LOVE',
  'OPEN_FRAME' = 'OPEN FRAME',
  'SPLIT' = 'SPLIT',
  'TIRE' = 'TIRE'
}
